---
---
  
<br>
<br>

## Job Market Paper

<font size="3">[<b>World Shocks, Commodity Prices and Domestic Inflation</b>](2ndPaper.pdf)</font> <br>

<div style="text-align: justify">
World shocks to global commodity prices can explain fluctuations in domestic inflation, but the extent to which these shocks affect inflation is debatable. Using a factor model with data on a set of 67 advanced and emerging countries, for the period 1970-2014, I extract the co-movements of the prices of several commodities to proxy for world prices. I then devise a structural vector autoregressive model in which world shocks affect these countries’ domestic economies through changes in common factors of commodity prices, and the world interest rate. Findings show that world shocks can explain between 26% and 38% of inflation fluctuations in the median country in the set considered in this study. These results have implications for monetary policymakers in that it highlights the need to use the co-movements of several commodity prices to assess the effects of world shocks on domestic inflation. Previous studies that used single world price vector autoregression models have been found to significantly underestimate the importance of world shocks for domestic business cycles. Similarly, I find that the fraction of the inflation variance explained by world shocks falls by more than half (below 13% in the median country) when a single world price is included in the model. This study extends the literature as it uses three factors of commodities to explain their effects on domestic inflation.

 </div>
<br>


## Working Papers
 <font size="3">[<b>Do Commodity Price Shocks matter for Estimating the Output Gap? </b>](3rdPaper.pdf)</font> <br>

<div style="text-align: justify">
This paper evaluates the importance of commodity price shocks in estimating the output gap. I use the Beveridge and Nelson decomposition method and compute the share of domestic and foreign shocks in the variance decomposition of the output gap. I devise a VAR model in which world shocks affect the output trend and the output gap through changes in commodity prices and global economic factors. I report the results for five advanced and ten emerging economies, over the 1980-2018 period. My results suggest that foreign shocks appear to be more important for the output gap, relative to the output trend, and emerging economies' output trends appear to be more affected by foreign shocks compared to advanced economies. Also, commodity price shocks account for much of the reported shares of foreign shocks in the output trend for both advanced and emerging economies. I also assess the reliability of estimated output gaps in predicting inflation, compared to the reliability of other output measures. I find that output gap estimates do relatively better in inflation forecasting compared to other specifications. This result highlights the need for using commodity price indices in assessing the effects of world shocks on the output gap. 	 
 


 <font size="3">[<b>The Impact of Income Inequality on Domestic Investment in Resource-Rich Countries </b>](1stPaper.pdf)</font> <br>

<div style="text-align: justify">

This paper examines a relation between income inequality, natural-resource rents and domestic investment in resource-rich countries. While previous studies have found that the unequal distribution of natural-resource rents has a negative impact on general economic performance, little is known about its direct implications for domestic investment. In this paper, I apply difference and system generalized method-of-moments estimators to a dynamic panel of 57 resource-rich countries, over the period 1982-2015. My findings show that, on average, countries with higher income inequality contribute relatively lower proportions of their natural-resource rents to domestic investment than do countries with lower income inequality. This result is robust to a variety of income-inequality measures, estimation approaches, and alternative specifications. The results could help resource-rich countries in their efforts to achieve higher growth using their resource endowments.

</div>
<br>